package com.example.ui.util

import com.example.ui.theme.AppLanguage

data class AppStringResources(
    val appName: String,
    val appSubtitle: String,
    val devotionalManager: String,
    val devotionalMantra: String,
    
    // Tabs
    val tabDashboard: String,
    val tabDonations: String,
    val tabExpenses: String,
    val tabHistory: String,
    
    // Header
    val allKirtans: String,
    val switchKirtan: String,
    val addNewKirtan: String,
    val shareReport: String,
    val settings: String,
    
    // Dashboard
    val netBalance: String,
    val availableFunds: String,
    val totalDonations: String,
    val totalExpenses: String,
    val donors: String,
    val entries: String,
    val cash: String,
    val upi: String,
    val quickActions: String,
    val addDonation: String,
    val addExpense: String,
    val recentDonations: String,
    val recentExpenses: String,
    val viewAll: String,
    val noDonations: String,
    val noExpenses: String,
    val categoryBreakdown: String,
    val kirtanStatusActive: String,
    val kirtanStatusCompleted: String,
    val organizerLabel: String,
    val locationLabel: String,
    val dateLabel: String,
    
    // Donations
    val donationHistoryTitle: String,
    val searchDonationsPlaceholder: String,
    val filterAll: String,
    val filterCash: String,
    val filterUpi: String,
    val filterWithPhone: String,
    val paymentReceived: String,
    val paymentNotReceived: String,
    val paymentStatus: String,
    val clearSearch: String,
    val viewReceipt: String,
    val edit: String,
    val delete: String,
    val noDonationsFound: String,
    val donorsFoundSuffix: String,
    val noDonorSearchMatch: String,
    val addDonationHint: String,
    
    // Expenses
    val searchExpensesPlaceholder: String,
    val allCategories: String,
    val paidTo: String,
    val noExpensesFound: String,
    val expensesFoundSuffix: String,
    val addExpenseHint: String,
    val billPrefix: String,
    val notePrefix: String,
    
    // History & Events
    val tabLogs: String,
    val tabKirtans: String,
    val searchLogsPlaceholder: String,
    val statusCompleted: String,
    val statusActive: String,
    val tapToSelect: String,
    val currentlySelected: String,
    val noLogsFound: String,
    val multipleKirtanTitle: String,
    val multipleKirtanDesc: String,
    val allKirtansDesc: String,
    val kirtanListTitle: String,
    
    // Add/Edit Donation Dialog
    val dialogAddDonationTitle: String,
    val dialogEditDonationTitle: String,
    val dialogAddDonationSubtitle: String,
    val receiptNumberLabel: String,
    val receiptNumberPlaceholder: String,
    val donorNameLabel: String,
    val donorNamePlaceholder: String,
    val donorNameError: String,
    val amountLabel: String,
    val amountPlaceholder: String,
    val amountError: String,
    val mobileLabel: String,
    val mobilePlaceholder: String,
    val paymentModeLabel: String,
    val paymentStatusHeader: String,
    val statusReceived: String,
    val statusReceivedSub: String,
    val statusNotReceived: String,
    val statusNotReceivedSub: String,
    val statusBadgeReceived: String,
    val statusBadgePending: String,
    val notesDonationLabel: String,
    val notesDonationPlaceholder: String,
    val receivedByLabel: String,
    val receivedByPlaceholder: String,
    val selectKirtanLabel: String,
    val saveDonationBtn: String,
    val updateDonationBtn: String,
    
    // Add/Edit Expense Dialog
    val dialogAddExpenseTitle: String,
    val dialogEditExpenseTitle: String,
    val dialogAddExpenseSubtitle: String,
    val expenseTitleLabel: String,
    val expenseTitlePlaceholder: String,
    val expenseTitleError: String,
    val categoryLabel: String,
    val paidToLabel: String,
    val paidToPlaceholder: String,
    val refExpenseLabel: String,
    val refExpensePlaceholder: String,
    val notesExpenseLabel: String,
    val notesExpensePlaceholder: String,
    val saveExpenseBtn: String,
    val updateExpenseBtn: String,
    
    // Add/Edit Kirtan Dialog
    val dialogAddKirtanTitle: String,
    val dialogEditKirtanTitle: String,
    val dialogAddKirtanSubtitle: String,
    val kirtanNameLabel: String,
    val kirtanNamePlaceholder: String,
    val kirtanNameError: String,
    val organizerInputLabel: String,
    val organizerInputPlaceholder: String,
    val locationInputLabel: String,
    val locationInputPlaceholder: String,
    val notesKirtanLabel: String,
    val notesKirtanPlaceholder: String,
    val saveKirtanBtn: String,
    val updateKirtanBtn: String,
    
    // Receipt Slip Dialog
    val receiptSlipHeader: String,
    val receiptSlipNo: String,
    val receiptDate: String,
    val receiptDonor: String,
    val receiptAmount: String,
    val receiptMode: String,
    val receiptMobile: String,
    val receiptKirtan: String,
    val receiptPurpose: String,
    val receiptReceivedBy: String,
    val shareReceiptWhatsApp: String,
    val shareReceiptGeneral: String,
    val closeBtn: String,
    val cancelBtn: String,
    val confirmBtn: String,
    
    // Delete Confirmation
    val deleteConfirmTitle: String,
    val deleteConfirmDonationMsg: String,
    val deleteConfirmExpenseMsg: String,
    val deleteConfirmKirtanMsg: String,
    
    // Transparency Report Dialog
    val transparencyReportTitle: String,
    val shareReportWhatsApp: String,
    val copyReportBtn: String,
    
    // Settings Dialog
    val settingsDialogTitle: String,
    val settingsDialogSubtitle: String,
    val languageSectionTitle: String,
    val themeSectionTitle: String,
    val paletteSectionTitle: String,
    val doneBtn: String,

    // Backup & Restore
    val backupSectionTitle: String,
    val autoBackupTitle: String,
    val autoBackupDesc: String,
    val lastBackupLabel: String,
    val backupNowBtn: String,
    val restoreSectionTitle: String,
    val restoreFromFileBtn: String,
    val localBackupsTitle: String,
    val noLocalBackups: String,
    val restoreBtn: String,
    val deleteBackupBtn: String,

    // Default Reset
    val resetSectionTitle: String,
    val resetBtn: String,
    val resetWarningTitle: String,
    val resetWarningMessage: String,
    val resetSampleBtn: String,
    val resetBlankBtn: String,
    
    // Receipt & Reports Titles
    val receiptTitle: String,
    val reportTitle: String,

    // Booking Menu
    val bookingOption: String,
    val bookingSubtitle: String,
    val bookingMenuTitle: String,
    val bookingMenuDesc: String,
    val openBookingMenu: String,
    val addBookingTitle: String,
    val editBookingTitle: String,
    val vendorNameLabel: String,
    val vendorNamePlaceholder: String,
    val vendorNameError: String,
    val contactNumberLabel: String,
    val contactNumberPlaceholder: String,
    val totalAmountLabel: String,
    val advancePaidLabel: String,
    val balanceDueLabel: String,
    val bookingStatusLabel: String,
    val bookingNotesLabel: String,
    val noBookingsCategory: String,
    val addBookingBtn: String,
    val saveBookingBtn: String,
    val statusConfirmed: String,
    val statusAdvancePaid: String,
    val statusPending: String,
    val totalBookingCommitment: String,
    val totalAdvancePaidTitle: String,
    val totalBalanceRemainingTitle: String,
    val callVendor: String,
    val shareBookingSlip: String
)

object Localization {
    fun get(language: AppLanguage): AppStringResources {
        return when (language) {
            AppLanguage.HINDI -> AppStringResources(
                appName = "Kirtan Seva",
                appSubtitle = "कीर्तन दान एवं खर्चा हिसाब",
                devotionalManager = "DEVOTIONAL MANAGER",
                devotionalMantra = "",
                
                tabDashboard = "डैशबोर्ड",
                tabDonations = "दान",
                tabExpenses = "खर्च",
                tabHistory = "इतिहास",
                
                allKirtans = "समस्त कीर्तन (कुल योग)",
                switchKirtan = "बदलें",
                addNewKirtan = "+ नया कीर्तन जोड़ें",
                shareReport = "रिपोर्ट साझा करें",
                settings = "सेटिंग्स",
                
                netBalance = "अवशेष राशि",
                availableFunds = "कुल संचित सेवा राशि",
                totalDonations = "कुल दान",
                totalExpenses = "कुल खर्च",
                donors = "दानदाता",
                entries = "मद",
                cash = "नकद",
                upi = "UPI",
                quickActions = "त्वरित सेवा",
                addDonation = "+ दान जोड़ें",
                addExpense = "- खर्च जोड़ें",
                recentDonations = "हाल ही में प्राप्त दान",
                recentExpenses = "हाल ही में हुए खर्च",
                viewAll = "सभी देखें",
                noDonations = "अभी तक कोई दान प्रविष्टि नहीं है",
                noExpenses = "अभी तक कोई खर्च प्रविष्टि नहीं है",
                categoryBreakdown = "श्रेणी अनुसार खर्च विवरण",
                kirtanStatusActive = "● सक्रिय",
                kirtanStatusCompleted = "✓ सम्पन्न",
                organizerLabel = "आयोजक:",
                locationLabel = "स्थान:",
                dateLabel = "दिनांक:",
                
                searchDonationsPlaceholder = "दानदाता का नाम या मोबाइल नंबर खोजें...",
                donationHistoryTitle = "दान इतिहास व रसीद सूची",
                filterAll = "सभी",
                filterCash = "💵 नकद",
                filterUpi = "⚡ UPI",
                filterWithPhone = "📞 मोबाइल वाले",
                paymentReceived = "प्राप्त",
                paymentNotReceived = "अप्राप्त",
                paymentStatus = "भुगतान स्थिति",
                clearSearch = "साफ़ करें",
                viewReceipt = "रसीद पर्ची",
                edit = "बदलें",
                delete = "हटाएं",
                noDonationsFound = "कोई दान रिकॉर्ड नहीं मिला",
                donorsFoundSuffix = "दानदाता मिले",
                noDonorSearchMatch = "से मिलता कोई दानदाता या मोबाइल नंबर नहीं है।",
                addDonationHint = "नीचे दिए गए '+' बटन से नया दान जोड़ें",
                
                searchExpensesPlaceholder = "खर्च मद या प्राप्तकर्ता खोजें...",
                allCategories = "सभी श्रेणियां",
                paidTo = "भुगतान:",
                noExpensesFound = "कोई खर्च रिकॉर्ड नहीं मिला",
                expensesFoundSuffix = "खर्च प्रविष्टियां मिलीं",
                addExpenseHint = "नीचे दिए गए '+' बटन से नया खर्च जोड़ें",
                billPrefix = "बिल / क्रमांक:",
                notePrefix = "नोट:",
                
                tabLogs = "पारदर्शिता लॉग्स",
                tabKirtans = "कीर्तन प्रबंधन",
                searchLogsPlaceholder = "लेनदेन खोजें (Search logs)...",
                statusCompleted = "✓ सम्पन्न",
                statusActive = "● सक्रिय",
                tapToSelect = "टैप करके चुनें",
                currentlySelected = "✓ वर्तमान चयनित",
                noLogsFound = "कोई लेनदेन रिकॉर्ड नहीं मिला",
                multipleKirtanTitle = "एकाधिक कीर्तन प्रबंधन",
                multipleKirtanDesc = "प्रत्येक कीर्तन का अलग-अलग चंदा व खर्च रिकॉर्ड रखें",
                allKirtansDesc = "सभी कीर्तनों का कुल दान एवं खर्च एक साथ देखें",
                kirtanListTitle = "आयोजित कीर्तन सूची",
                
                dialogAddDonationTitle = "दान रसीद बनाएं",
                dialogEditDonationTitle = "दान विवरण संपादित करें",
                dialogAddDonationSubtitle = "दान एवं रसीद विवरण दर्ज करें",
                receiptNumberLabel = "रसीद संख्या (Receipt No / Slip No) *",
                receiptNumberPlaceholder = "उदा. REC-101 / पर्ची संख्या",
                donorNameLabel = "दानदाता का नाम *",
                donorNamePlaceholder = "उदा. रमेश कुमार शर्मा",
                donorNameError = "कृपया दानदाता का नाम दर्ज करें",
                amountLabel = "सहयोग राशि (₹) *",
                amountPlaceholder = "उदा. 501",
                amountError = "कृपया वैध राशि दर्ज करें (> 0)",
                mobileLabel = "फ़ोन / मोबाइल नंबर",
                mobilePlaceholder = "10 अंकों का मोबाइल नंबर",
                paymentModeLabel = "भुगतान माध्यम:",
                paymentStatusHeader = "भुगतान स्थिति:",
                statusReceived = "भुगतान प्राप्त",
                statusReceivedSub = "जमा (Received)",
                statusNotReceived = "भुगतान अप्राप्त",
                statusNotReceivedSub = "बाक़ी (Pending)",
                statusBadgeReceived = "प्राप्त",
                statusBadgePending = "अप्राप्त",
                notesDonationLabel = "सेवा संकल्प / टिप्पणी",
                notesDonationPlaceholder = "उदा. भोग सेवा, परिवार कल्याण हेतु",
                receivedByLabel = "प्राप्तकर्ता (सेवादार का नाम)",
                receivedByPlaceholder = "उदा. सेवादार का नाम",
                selectKirtanLabel = "कीर्तन चयन करें:",
                saveDonationBtn = "दान रसीद सुरक्षित करें",
                updateDonationBtn = "अपडेट करें",
                
                dialogAddExpenseTitle = "खर्च प्रविष्टि",
                dialogEditExpenseTitle = "खर्च विवरण संपादित करें",
                dialogAddExpenseSubtitle = "खर्च एवं वाउचर विवरण दर्ज करें",
                expenseTitleLabel = "खर्च का नाम / मद *",
                expenseTitlePlaceholder = "उदा. टेंट, साउंड, प्रसाद सामग्री, फूल",
                expenseTitleError = "कृपया खर्च का नाम दर्ज करें",
                categoryLabel = "खर्च की श्रेणी:",
                paidToLabel = "भुगतान पाने वाला (Vendor / व्यक्ति)",
                paidToPlaceholder = "उदा. शर्मा टेंट हाउस, पं. जी",
                refExpenseLabel = "बिल / वाउचर / UTR क्रमांक",
                refExpensePlaceholder = "उदा. BILL-891, UPI Ref",
                notesExpenseLabel = "विवरण / विशेष टिप्पणी",
                notesExpensePlaceholder = "उदा. अग्रिम भुगतान, पूरा हिसाब",
                saveExpenseBtn = "खर्च सुरक्षित करें",
                updateExpenseBtn = "खर्च अपडेट करें",
                
                dialogAddKirtanTitle = "नया कीर्तन जोड़ें",
                dialogEditKirtanTitle = "कीर्तन विवरण संपादित करें",
                dialogAddKirtanSubtitle = "आयोजन की जानकारी दर्ज करें",
                kirtanNameLabel = "कीर्तन / संकीर्तन का नाम *",
                kirtanNamePlaceholder = "उदा. श्री श्याम संकीर्तन महोत्सव",
                kirtanNameError = "कृपया कीर्तन का नाम दर्ज करें",
                organizerInputLabel = "आयोजक / सेवा समिति",
                organizerInputPlaceholder = "उदा. श्याम मित्र मंडल",
                locationInputLabel = "स्थान / स्थल",
                locationInputPlaceholder = "उदा. कम्युनिटी हॉल, मुख्य बाजार",
                notesKirtanLabel = "टिप्पणी / विवरण",
                notesKirtanPlaceholder = "उदा. वार्षिक उत्सव, विशेष आरती",
                saveKirtanBtn = "कीर्तन सुरक्षित करें",
                updateKirtanBtn = "कीर्तन अपडेट करें",
                
                receiptSlipHeader = "॥ श्री कीर्तन सेवा दान रसीद ॥",
                receiptSlipNo = "रसीद सं:",
                receiptDate = "दिनांक:",
                receiptDonor = "दानदाता:",
                receiptAmount = "सहयोग राशि:",
                receiptMode = "माध्यम:",
                receiptMobile = "मोबाइल:",
                receiptKirtan = "कीर्तन आयोजन:",
                receiptPurpose = "सेवा संकल्प:",
                receiptReceivedBy = "प्राप्तकर्ता:",
                shareReceiptWhatsApp = "व्हाट्सएप पर रसीद भेजें",
                shareReceiptGeneral = "शेयर करें",
                closeBtn = "बंद करें",
                cancelBtn = "रद्द करें",
                confirmBtn = "पुष्टि करें",
                
                deleteConfirmTitle = "हटाने की पुष्टि",
                deleteConfirmDonationMsg = "क्या आप इस दान प्रविष्टि को हटाना चाहते हैं?",
                deleteConfirmExpenseMsg = "क्या आप इस खर्च प्रविष्टि को हटाना चाहते हैं?",
                deleteConfirmKirtanMsg = "क्या आप इस कीर्तन को हटाना चाहते हैं? इसके सभी संबंधित दान व खर्च भी हट जाएंगे।",
                
                transparencyReportTitle = "पारदर्शिता हिसाब-किताब रिपोर्ट",
                shareReportWhatsApp = "व्हाट्सएप पर रिपोर्ट साझा करें",
                copyReportBtn = "रिपोर्ट कॉपी करें",
                
                settingsDialogTitle = "सेटिंग्स",
                settingsDialogSubtitle = "ऐप प्राथमिकताएं, भाषा एवं बैकअप",
                languageSectionTitle = "भाषा चुनें (Select Language)",
                themeSectionTitle = "थीम मोड (Theme Mode)",
                paletteSectionTitle = "रंग शैली (Devotional Palette)",
                doneBtn = "लागू करें (Done)",

                backupSectionTitle = "स्वचालित बैकअप (Auto Daily Backup)",
                autoBackupTitle = "दैनिक स्वचालित बैकअप",
                autoBackupDesc = "प्रतिदिन फोन में बैकअप सुरक्षित रखें",
                lastBackupLabel = "अंतिम बैकअप:",
                backupNowBtn = "📱 तुरंत मोबाइल में बैकअप लें",
                restoreSectionTitle = "मोबाइल से रीस्टोर करें",
                restoreFromFileBtn = "📂 मोबाइल फ़ाइल से रीस्टोर करें (.json)",
                localBackupsTitle = "फोन में उपलब्ध स्थानीय बैकअप",
                noLocalBackups = "कोई स्थानीय बैकअप फ़ाइल नहीं मिली",
                restoreBtn = "रीस्टोर करें",
                deleteBackupBtn = "हटाएं",

                resetSectionTitle = "डिफ़ॉल्ट रीसेट (Default Reset)",
                resetBtn = "⚠️ डिफ़ॉल्ट रीसेट करें",
                resetWarningTitle = "डिफ़ॉल्ट रीसेट की पुष्टि",
                resetWarningMessage = "क्या आप वास्तव में सारा डेटा रीसेट करना चाहते हैं? आपकी सुरक्षा के लिए वर्तमान डेटा का एक ऑटो-बैकअप सुरक्षित कर लिया जाएगा।",
                resetSampleBtn = "नमूना डेटा के साथ रीसेट",
                resetBlankBtn = "पूर्णतः रिक्त रीसेट (खाली करें)",
                
                receiptTitle = "॥ श्री कीर्तन सेवा दान रसीद ॥",
                reportTitle = "पारदर्शिता हिसाब-किताब रिपोर्ट",

                bookingOption = "बुकिंग (Booking)",
                bookingSubtitle = "गार्डन, सिंगर्स, साउंड, श्रृंगार, हलवाई एवं अन्य 13 सेवाएं",
                bookingMenuTitle = "बुकिंग मेन्यू (Event Services)",
                bookingMenuDesc = "कीर्तन एवं धार्मिक आयोजन हेतु सभी सेवा प्रदाताओं की व्यवस्था",
                openBookingMenu = "मेन्यू देखें",
                addBookingTitle = "नई बुकिंग जोड़ें",
                editBookingTitle = "बुकिंग संपादित करें",
                vendorNameLabel = "सेवा प्रदाता / वेंडर का नाम",
                vendorNamePlaceholder = "उदा. श्री राधे टेंट & गार्डन / पं. राहुल शर्मा",
                vendorNameError = "कृपया वेंडर अथवा सेवा प्रदाता का नाम दर्ज करें",
                contactNumberLabel = "मोबाइल नंबर",
                contactNumberPlaceholder = "उदा. 9876543210",
                totalAmountLabel = "कुल तय राशि (₹)",
                advancePaidLabel = "एडवांस जमा राशि (₹)",
                balanceDueLabel = "शेष देय राशि",
                bookingStatusLabel = "बुकिंग स्थिति",
                bookingNotesLabel = "विशेष विवरण / आवश्यकताएं",
                noBookingsCategory = "इस श्रेणी में अभी कोई बुकिंग दर्ज नहीं है। नीचे बटन दबाकर नई बुकिंग जोड़ें।",
                addBookingBtn = "+ बुकिंग जोड़ें",
                saveBookingBtn = "बुकिंग सुरक्षित करें",
                statusConfirmed = "पुष्ट (Confirmed)",
                statusAdvancePaid = "एडवांस दिया (Advance Paid)",
                statusPending = "लंबित (Pending)",
                totalBookingCommitment = "कुल बुकिंग बजट",
                totalAdvancePaidTitle = "कुल दिया गया एडवांस",
                totalBalanceRemainingTitle = "कुल बकाया शेष",
                callVendor = "कॉल करें",
                shareBookingSlip = "बुकिंग विवरण साझा करें"
            )
            
            AppLanguage.ENGLISH -> AppStringResources(
                appName = "Kirtan Seva",
                appSubtitle = "Devotional Accounts & Seva Register",
                devotionalManager = "DEVOTIONAL MANAGER",
                devotionalMantra = "",
                
                tabDashboard = "Dashboard",
                tabDonations = "Donations",
                tabExpenses = "Expenses",
                tabHistory = "History",
                
                allKirtans = "All Kirtans Aggregate",
                switchKirtan = "Switch",
                addNewKirtan = "+ Add New Kirtan",
                shareReport = "Share Report",
                settings = "Settings",
                
                netBalance = "Net Balance",
                availableFunds = "Available Seva Funds",
                totalDonations = "Total Donations",
                totalExpenses = "Total Expenses",
                donors = "Donors",
                entries = "Entries",
                cash = "Cash",
                upi = "UPI",
                quickActions = "Quick Actions",
                addDonation = "+ Add Donation",
                addExpense = "- Add Expense",
                recentDonations = "Recent Donations",
                recentExpenses = "Recent Expenses",
                viewAll = "View All",
                noDonations = "No donations recorded yet",
                noExpenses = "No expenses recorded yet",
                categoryBreakdown = "Expense Breakdown by Category",
                kirtanStatusActive = "● Active",
                kirtanStatusCompleted = "✓ Completed",
                organizerLabel = "Organizer:",
                locationLabel = "Location:",
                dateLabel = "Date:",
                
                searchDonationsPlaceholder = "Search donor by name or mobile...",
                donationHistoryTitle = "Donation History Log",
                filterAll = "All",
                filterCash = "💵 Cash",
                filterUpi = "⚡ UPI",
                filterWithPhone = "📞 With Mobile",
                paymentReceived = "Received",
                paymentNotReceived = "Pending",
                paymentStatus = "Payment Status",
                clearSearch = "Clear",
                viewReceipt = "Receipt Slip",
                edit = "Edit",
                delete = "Delete",
                noDonationsFound = "No donations found",
                donorsFoundSuffix = "donors found",
                noDonorSearchMatch = "matches no donor or phone number.",
                addDonationHint = "Tap the '+' button below to record a donation",
                
                searchExpensesPlaceholder = "Search expense or payee...",
                allCategories = "All Categories",
                paidTo = "Paid to:",
                noExpensesFound = "No expenses found",
                expensesFoundSuffix = "expenses found",
                addExpenseHint = "Tap the '+' button below to record an expense",
                billPrefix = "Bill / Ref:",
                notePrefix = "Note:",
                
                tabLogs = "Audit Logs",
                tabKirtans = "Kirtan Events",
                searchLogsPlaceholder = "Search transaction logs...",
                statusCompleted = "✓ Completed",
                statusActive = "● Active",
                tapToSelect = "Tap to select",
                currentlySelected = "✓ Currently Selected",
                noLogsFound = "No transactions found",
                multipleKirtanTitle = "Multiple Kirtan Management",
                multipleKirtanDesc = "Keep separate donation & expense records for each devotional event",
                allKirtansDesc = "View aggregated total donations & expenses across all events",
                kirtanListTitle = "Organized Kirtan Events",
                
                dialogAddDonationTitle = "Make Donation Receipt",
                dialogEditDonationTitle = "Edit Donation Details",
                dialogAddDonationSubtitle = "Enter donation and receipt details",
                receiptNumberLabel = "Receipt Number / Slip No *",
                receiptNumberPlaceholder = "e.g. REC-101 / Slip No",
                donorNameLabel = "Donor Name *",
                donorNamePlaceholder = "e.g. Ramesh Kumar",
                donorNameError = "Please enter donor name",
                amountLabel = "Donation Amount (₹) *",
                amountPlaceholder = "e.g. 501",
                amountError = "Please enter a valid amount (> 0)",
                mobileLabel = "Phone / Mobile Number",
                mobilePlaceholder = "10-digit mobile number",
                paymentModeLabel = "Payment Mode:",
                paymentStatusHeader = "Payment Status:",
                statusReceived = "Payment Received",
                statusReceivedSub = "Collected (Received)",
                statusNotReceived = "Payment Pending",
                statusNotReceivedSub = "Pending / Pledge",
                statusBadgeReceived = "Received",
                statusBadgePending = "Pending",
                notesDonationLabel = "Purpose / Notes",
                notesDonationPlaceholder = "e.g. Bhog Seva, Family Blessing",
                receivedByLabel = "Received By (Sevak Name)",
                receivedByPlaceholder = "e.g. Sevak Name",
                selectKirtanLabel = "Select Kirtan Event:",
                saveDonationBtn = "Save Receipt",
                updateDonationBtn = "Update Details",
                
                dialogAddExpenseTitle = "Add Expense Entry",
                dialogEditExpenseTitle = "Edit Expense Entry",
                dialogAddExpenseSubtitle = "Enter expense and voucher details",
                expenseTitleLabel = "Expense Title / Purpose *",
                expenseTitlePlaceholder = "e.g. Tent, Sound, Prasad, Flowers",
                expenseTitleError = "Please enter expense purpose",
                categoryLabel = "Expense Category:",
                paidToLabel = "Paid To (Vendor / Person)",
                paidToPlaceholder = "e.g. Sharma Tent House, Singer",
                refExpenseLabel = "Bill / Voucher / UTR Ref",
                refExpensePlaceholder = "e.g. BILL-891, UPI Ref",
                notesExpenseLabel = "Notes / Remarks",
                notesExpensePlaceholder = "e.g. Advance paid, full settlement",
                saveExpenseBtn = "Save Expense",
                updateExpenseBtn = "Update Expense",
                
                dialogAddKirtanTitle = "Add New Kirtan Event",
                dialogEditKirtanTitle = "Edit Kirtan Event",
                dialogAddKirtanSubtitle = "Enter devotional event details",
                kirtanNameLabel = "Kirtan / Event Name *",
                kirtanNamePlaceholder = "e.g. Shri Shyam Sankirtan Mahotsav",
                kirtanNameError = "Please enter kirtan event name",
                organizerInputLabel = "Organizer / Committee",
                organizerInputPlaceholder = "e.g. Shyam Mitra Mandal",
                locationInputLabel = "Location / Venue",
                locationInputPlaceholder = "e.g. Community Hall, Main Road",
                notesKirtanLabel = "Notes / Details",
                notesKirtanPlaceholder = "e.g. Annual celebration, special aarti",
                saveKirtanBtn = "Save Kirtan",
                updateKirtanBtn = "Update Kirtan",
                
                receiptSlipHeader = "|| Shri Kirtan Seva Donation Receipt ||",
                receiptSlipNo = "Receipt No:",
                receiptDate = "Date:",
                receiptDonor = "Donor Name:",
                receiptAmount = "Donation Amount:",
                receiptMode = "Payment Mode:",
                receiptMobile = "Mobile:",
                receiptKirtan = "Kirtan Event:",
                receiptPurpose = "Purpose / Sankalp:",
                receiptReceivedBy = "Received By:",
                shareReceiptWhatsApp = "Share Receipt on WhatsApp",
                shareReceiptGeneral = "Share",
                closeBtn = "Close",
                cancelBtn = "Cancel",
                confirmBtn = "Confirm",
                
                deleteConfirmTitle = "Confirm Deletion",
                deleteConfirmDonationMsg = "Are you sure you want to delete this donation entry?",
                deleteConfirmExpenseMsg = "Are you sure you want to delete this expense entry?",
                deleteConfirmKirtanMsg = "Are you sure you want to delete this kirtan? All linked donations and expenses will also be deleted.",
                
                transparencyReportTitle = "Devotional Transparency Report",
                shareReportWhatsApp = "Share Report on WhatsApp",
                copyReportBtn = "Copy Report Text",
                
                settingsDialogTitle = "Settings",
                settingsDialogSubtitle = "Preferences, Language & Data Backup",
                languageSectionTitle = "App Language",
                themeSectionTitle = "Theme Mode",
                paletteSectionTitle = "Devotional Color Palette",
                doneBtn = "Done",

                backupSectionTitle = "Automatic Daily Backup in Mobile",
                autoBackupTitle = "Daily Automatic Backup",
                autoBackupDesc = "Safely snapshot data locally every day",
                lastBackupLabel = "Last Backup:",
                backupNowBtn = "📱 Backup Now to Mobile",
                restoreSectionTitle = "Restore from Mobile",
                restoreFromFileBtn = "📂 Restore from Phone File (.json)",
                localBackupsTitle = "Device Local Backups",
                noLocalBackups = "No local backup snapshots found",
                restoreBtn = "Restore",
                deleteBackupBtn = "Delete",

                resetSectionTitle = "Default Reset",
                resetBtn = "⚠️ Reset to Default",
                resetWarningTitle = "Confirm Default Reset",
                resetWarningMessage = "Are you sure you want to reset all data? A safety backup will automatically be saved on your device first.",
                resetSampleBtn = "Reset with Sample Data",
                resetBlankBtn = "Reset to Blank (Clean State)",
                
                receiptTitle = "|| Shri Kirtan Seva Donation Receipt ||",
                reportTitle = "Devotional Transparency Report",

                bookingOption = "Booking",
                bookingSubtitle = "Garden/Hall, Singers, Sound, Light, Halwai & 13 Services",
                bookingMenuTitle = "Booking Services Menu",
                bookingMenuDesc = "Complete vendor management for kirtan and devotional events",
                openBookingMenu = "Open Menu",
                addBookingTitle = "Add New Booking",
                editBookingTitle = "Edit Booking",
                vendorNameLabel = "Vendor / Service Provider Name",
                vendorNamePlaceholder = "e.g. Radhe Tent & Garden / Pt. Rahul Sharma",
                vendorNameError = "Please enter vendor or artist name",
                contactNumberLabel = "Contact Number",
                contactNumberPlaceholder = "e.g. 9876543210",
                totalAmountLabel = "Total Agreed Amount (₹)",
                advancePaidLabel = "Advance Paid (₹)",
                balanceDueLabel = "Balance Due",
                bookingStatusLabel = "Booking Status",
                bookingNotesLabel = "Notes & Requirements",
                noBookingsCategory = "No bookings recorded for this service category yet. Tap below to add a new booking.",
                addBookingBtn = "+ Add Booking",
                saveBookingBtn = "Save Booking",
                statusConfirmed = "Confirmed",
                statusAdvancePaid = "Advance Paid",
                statusPending = "Pending",
                totalBookingCommitment = "Total Bookings Budget",
                totalAdvancePaidTitle = "Total Advance Paid",
                totalBalanceRemainingTitle = "Total Balance Due",
                callVendor = "Call Vendor",
                shareBookingSlip = "Share Booking Slip"
            )
            
            AppLanguage.HINGLISH -> AppStringResources(
                appName = "Kirtan Seva",
                appSubtitle = "Kirtan Daan & Kharcha Hisaab",
                devotionalManager = "DEVOTIONAL MANAGER",
                devotionalMantra = "",
                
                tabDashboard = "Dashboard",
                tabDonations = "Daan (दान)",
                tabExpenses = "Kharcha (खर्च)",
                tabHistory = "History",
                
                allKirtans = "Sabhi Kirtan (Combined)",
                switchKirtan = "Badlein",
                addNewKirtan = "+ Naya Kirtan Jodein",
                shareReport = "Report Share Karein",
                settings = "Settings",
                
                netBalance = "Net Bachat",
                availableFunds = "Total Available Seva Fund",
                totalDonations = "Kul Daan",
                totalExpenses = "Kul Kharcha",
                donors = "Dan-data",
                entries = "Entries",
                cash = "Cash",
                upi = "UPI",
                quickActions = "Quick Actions",
                addDonation = "+ Daan Jodein",
                addExpense = "- Kharcha Jodein",
                recentDonations = "Haal hi mein prapt Daan",
                recentExpenses = "Haal hi ke Kharche",
                viewAll = "Sabhi Dekhein",
                noDonations = "Abhi tak koi daan record nahi hai",
                noExpenses = "Abhi tak koi kharcha record nahi hai",
                categoryBreakdown = "Category-wise Kharcha Hisaab",
                kirtanStatusActive = "● Active",
                kirtanStatusCompleted = "✓ Sampann",
                organizerLabel = "Aayojak:",
                locationLabel = "Sthan:",
                dateLabel = "Date:",
                
                searchDonationsPlaceholder = "Dan-data naam ya mobile se khojein...",
                donationHistoryTitle = "Daan History Log",
                filterAll = "Sabhi",
                filterCash = "💵 Cash",
                filterUpi = "⚡ UPI",
                filterWithPhone = "📞 Mobile Wale",
                paymentReceived = "Received",
                paymentNotReceived = "Pending",
                paymentStatus = "Payment Status",
                clearSearch = "Clear",
                viewReceipt = "Slip Dekhein",
                edit = "Edit",
                delete = "Delete",
                noDonationsFound = "Koi daan record nahi mila",
                donorsFoundSuffix = "dan-data mile",
                noDonorSearchMatch = "se milta koi record nahi mila.",
                addDonationHint = "Neeche diye '+' button se naya daan jodein",
                
                searchExpensesPlaceholder = "Kharcha ya payee ka naam khojein...",
                allCategories = "Sabhi Categories",
                paidTo = "Paid to:",
                noExpensesFound = "Koi kharcha record nahi mila",
                expensesFoundSuffix = "kharche mile",
                addExpenseHint = "Neeche diye '+' button se naya kharcha jodein",
                billPrefix = "Bill / Txn:",
                notePrefix = "Note:",
                
                tabLogs = "Audit Logs",
                tabKirtans = "Kirtan Prabandhan",
                searchLogsPlaceholder = "Transactions khojein...",
                statusCompleted = "✓ Sampann",
                statusActive = "● Active",
                tapToSelect = "Tap karke chunein",
                currentlySelected = "✓ Currently Selected",
                noLogsFound = "Koi record nahi mila",
                multipleKirtanTitle = "Multiple Kirtan Management",
                multipleKirtanDesc = "Har kirtan ka alag daan aur kharcha record rakhein",
                allKirtansDesc = "Sabhi kirtano ka total daan aur kharcha ek saath dekhein",
                kirtanListTitle = "Kirtan Events List",
                
                dialogAddDonationTitle = "Daan Receipt Banayein",
                dialogEditDonationTitle = "Daan Details Edit Karein",
                dialogAddDonationSubtitle = "Daan aur receipt details enter karein",
                receiptNumberLabel = "Receipt Number (Slip No) *",
                receiptNumberPlaceholder = "e.g. REC-101 / Slip No",
                donorNameLabel = "Dan-data Ka Naam *",
                donorNamePlaceholder = "e.g. Ramesh Kumar",
                donorNameError = "Kripya dan-data ka naam dalein",
                amountLabel = "Seva Rashi (₹) *",
                amountPlaceholder = "e.g. 501",
                amountError = "Kripya valid amount dalein (> 0)",
                mobileLabel = "Phone / Mobile Number",
                mobilePlaceholder = "10-digit mobile number",
                paymentModeLabel = "Payment Mode:",
                paymentStatusHeader = "Payment Status:",
                statusReceived = "Payment Received",
                statusReceivedSub = "Rashi Jama (Mila)",
                statusNotReceived = "Payment Pending",
                statusNotReceivedSub = "Baqi (Pending)",
                statusBadgeReceived = "Received",
                statusBadgePending = "Pending",
                notesDonationLabel = "Seva Sankalp / Notes",
                notesDonationPlaceholder = "e.g. Bhog Seva, Blessing",
                receivedByLabel = "Praptkarta (Sevak Naam)",
                receivedByPlaceholder = "e.g. Sevak Naam",
                selectKirtanLabel = "Kirtan Select Karein:",
                saveDonationBtn = "Receipt Save Karein",
                updateDonationBtn = "Update Karein",
                
                dialogAddExpenseTitle = "Kharcha Entry Jodein",
                dialogEditExpenseTitle = "Kharcha Edit Karein",
                dialogAddExpenseSubtitle = "Kharcha & voucher details enter karein",
                expenseTitleLabel = "Kharcha Item / Mad *",
                expenseTitlePlaceholder = "e.g. Tent, Sound, Prasad, Flowers",
                expenseTitleError = "Kripya kharcha ka naam dalein",
                categoryLabel = "Kharcha Category:",
                paidToLabel = "Payment Paane Wala (Vendor / Person)",
                paidToPlaceholder = "e.g. Sharma Tent House, Singer",
                refExpenseLabel = "Bill / Voucher / UTR Ref",
                refExpensePlaceholder = "e.g. BILL-891, UPI Ref",
                notesExpenseLabel = "Details / Remarks",
                notesExpensePlaceholder = "e.g. Advance payment, settlement",
                saveExpenseBtn = "Kharcha Save Karein",
                updateExpenseBtn = "Kharcha Update Karein",
                
                dialogAddKirtanTitle = "Naya Kirtan Jodein",
                dialogEditKirtanTitle = "Kirtan Details Edit Karein",
                dialogAddKirtanSubtitle = "Event details enter karein",
                kirtanNameLabel = "Kirtan / Event Ka Naam *",
                kirtanNamePlaceholder = "e.g. Shri Shyam Sankirtan Mahotsav",
                kirtanNameError = "Kripya kirtan ka naam dalein",
                organizerInputLabel = "Aayojak / Committee",
                organizerInputPlaceholder = "e.g. Shyam Mitra Mandal",
                locationInputLabel = "Sthan / Venue",
                locationInputPlaceholder = "e.g. Community Hall, Main Road",
                notesKirtanLabel = "Notes / Details",
                notesKirtanPlaceholder = "e.g. Annual celebration, Aarti",
                saveKirtanBtn = "Kirtan Save Karein",
                updateKirtanBtn = "Kirtan Update Karein",
                
                receiptSlipHeader = "॥ Shri Kirtan Seva Daan Rasid ॥",
                receiptSlipNo = "Receipt No:",
                receiptDate = "Date:",
                receiptDonor = "Dan-data:",
                receiptAmount = "Seva Rashi:",
                receiptMode = "Payment Mode:",
                receiptMobile = "Mobile:",
                receiptKirtan = "Kirtan Aayojan:",
                receiptPurpose = "Seva Sankalp:",
                receiptReceivedBy = "Praptkarta:",
                shareReceiptWhatsApp = "WhatsApp par Receipt Bhejein",
                shareReceiptGeneral = "Share Karein",
                closeBtn = "Close",
                cancelBtn = "Cancel",
                confirmBtn = "Confirm Karein",
                
                deleteConfirmTitle = "Delete Confirmation",
                deleteConfirmDonationMsg = "Kya aap is daan entry ko delete karna chahte hain?",
                deleteConfirmExpenseMsg = "Kya aap is kharcha entry ko delete karna chahte hain?",
                deleteConfirmKirtanMsg = "Kya aap is kirtan ko delete karna chahte hain? Iske sabhi daan aur kharche bhi delete ho jayenge.",
                
                transparencyReportTitle = "Kirtan Hisaab-Kitaab Report",
                shareReportWhatsApp = "WhatsApp par Report Bhejein",
                copyReportBtn = "Report Copy Karein",
                
                settingsDialogTitle = "Settings",
                settingsDialogSubtitle = "Preferences, Bhasha & Data Backup",
                languageSectionTitle = "Bhasha Chunein (Select Language)",
                themeSectionTitle = "Theme Mode",
                paletteSectionTitle = "Rang Shaili (Color Palette)",
                doneBtn = "Ho Gaya (Done)",

                backupSectionTitle = "Daily Auto Backup Mobile Mein",
                autoBackupTitle = "Daily Auto Backup",
                autoBackupDesc = "Rozana phone mein data auto-save karein",
                lastBackupLabel = "Aakhri Backup:",
                backupNowBtn = "📱 Mobile mein abhi Backup lein",
                restoreSectionTitle = "Mobile Se Restore Karein",
                restoreFromFileBtn = "📂 Mobile File se Restore (.json)",
                localBackupsTitle = "Phone Mein Saved Backups",
                noLocalBackups = "Koi local backup nahi mila",
                restoreBtn = "Restore Karein",
                deleteBackupBtn = "Delete",

                resetSectionTitle = "Default Reset",
                resetBtn = "⚠️ Default Reset Karein",
                resetWarningTitle = "Default Reset Confirmation",
                resetWarningMessage = "Kya aap saara data default reset karna chahte hain? Pehle ek safety backup phone mein auto-save ho jayega.",
                resetSampleBtn = "Sample Data ke saath Reset",
                resetBlankBtn = "Bilkul Saaf / Khali Reset",
                
                receiptTitle = "॥ Shri Kirtan Seva Daan Rasid ॥",
                reportTitle = "Kirtan Hisaab-Kitaab Report",

                bookingOption = "Booking (बुकिंग)",
                bookingSubtitle = "Garden, Singers, Sound, Halwai aur 13 Services ka hisaab",
                bookingMenuTitle = "Booking Services Menu",
                bookingMenuDesc = "Kirtan ke sabhi vendor aur seva booking ka hisaab",
                openBookingMenu = "Menu Dekhein",
                addBookingTitle = "Nayi Booking Jodein",
                editBookingTitle = "Booking Edit Karein",
                vendorNameLabel = "Vendor / Artist ka Naam",
                vendorNamePlaceholder = "Jaise: Radhe Sound / Pt. Sharma ji",
                vendorNameError = "Kripya vendor ya artist ka naam likhein",
                contactNumberLabel = "Mobile Number",
                contactNumberPlaceholder = "Jaise: 9876543210",
                totalAmountLabel = "Kul Tay Raashi (₹)",
                advancePaidLabel = "Advance Diya (₹)",
                balanceDueLabel = "Baqaya Raashi",
                bookingStatusLabel = "Booking Status",
                bookingNotesLabel = "Notes / Khaas zarooratein",
                noBookingsCategory = "Is category mein abhi koi booking nahi hai. Neeche button daba kar nayi booking jodein.",
                addBookingBtn = "+ Booking Jodein",
                saveBookingBtn = "Booking Save Karein",
                statusConfirmed = "Confirmed (पुष्ट)",
                statusAdvancePaid = "Advance Diya",
                statusPending = "Pending (बाकी)",
                totalBookingCommitment = "Kul Booking Budget",
                totalAdvancePaidTitle = "Total Advance Diya",
                totalBalanceRemainingTitle = "Total Baqaya",
                callVendor = "Call Karein",
                shareBookingSlip = "Booking Share Karein"
            )
        }
    }
}
